---
- name: Remove the subscription warning
  ansible.builtin.replace:
    path: "{{ pve_no_subscription_proxmoxlib_path }}"
    regexp: '^(\s*)Ext\.Msg\.show(\(\{\s*title\: gettext\(''No valid subscription''\),\n)'
    replace: '\1void\2'
  notify:
    - Restart pveproxy

# Proxmox repositories

- name: Remove pve-enterprise repository
  ansible.builtin.apt_repository:
    repo: "deb https://enterprise.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-enterprise"
    update_cache: false
    state: absent

- name: Add pve-no-subscription repo to the /etc/apt/sources.list
  ansible.builtin.apt_repository:
    repo: "deb http://download.proxmox.com/debian/pve {{ ansible_distribution_release }} pve-no-subscription"
    update_cache: false
    filename: pve-no-subscription
    state: present

# Ceph Squid repositories

- name: Remove Ceph Squid enterprise repository
  ansible.builtin.apt_repository:
    repo: "deb https://enterprise.proxmox.com/debian/ceph-squid {{ ansible_distribution_release }} enterprise"
    update_cache: false
    state: absent
  register: squid

- name: Add Ceph Squid no-subscription repository
  ansible.builtin.apt_repository:
    repo: "deb http://download.proxmox.com/debian/ceph-squid {{ ansible_distribution_release }} no-subscription"
    update_cache: false
    filename: ceph
    state: present
  when: squid.changed

# Ceph Reef repositories

- name: Remove Ceph Reef enterprise repository
  ansible.builtin.apt_repository:
    repo: "deb https://enterprise.proxmox.com/debian/ceph-reef {{ ansible_distribution_release }} enterprise"
    update_cache: false
    state: absent
  register: reef

- name: Add Ceph Reef no-subscription repository
  ansible.builtin.apt_repository:
    repo: "deb http://download.proxmox.com/debian/ceph-reef {{ ansible_distribution_release }} no-subscription"
    update_cache: false
    filename: ceph
    state: present
  when: reef.changed